AWSTemplateFormatVersion: 2010-09-09 
Resources:
  MyBucket:
    Type: 'AWS::S3::Bucket' 
    Properties:
      BucketName: !Sub tagsbucket-${AWS::AccountId} 
      Tags: [{"Key":"Value"}] 
      'Fn::Transform':
        - Name: 'AWS::Include'
          Parameters:
            Location: !Sub s3://codedeploy-nvirgina-${AWS::AccountId}-bucket/MyTags.yml